/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChampionshipRouteImport } from './routes/_championship'
import { Route as ArchivIndexRouteImport } from './routes/archiv.index'
import { Route as ArchivSlugRouteImport } from './routes/archiv.$slug'
import { Route as ChampionshipTabelleRouteImport } from './routes/_championship/tabelle'
import { Route as ChampionshipZusatzfragenRouteRouteImport } from './routes/_championship/zusatzfragen/route'
import { Route as ChampionshipIndexRouteRouteImport } from './routes/_championship/index/route'
import { Route as ChampionshipTippsChar123SlugChar125RouteRouteImport } from './routes/_championship/tipps.{-$slug}/route'
import { Route as ChampionshipSpieleNrRouteRouteImport } from './routes/_championship/spiele.$nr/route'
import { Route as ChampionshipSpieleIndexRouteRouteImport } from './routes/_championship/spiele.index/route'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionshipRoute = ChampionshipRouteImport.update({
  id: '/_championship',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivIndexRoute = ArchivIndexRouteImport.update({
  id: '/archiv/',
  path: '/archiv/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivSlugRoute = ArchivSlugRouteImport.update({
  id: '/archiv/$slug',
  path: '/archiv/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionshipTabelleRoute = ChampionshipTabelleRouteImport.update({
  id: '/tabelle',
  path: '/tabelle',
  getParentRoute: () => ChampionshipRoute,
} as any)
const ChampionshipZusatzfragenRouteRoute =
  ChampionshipZusatzfragenRouteRouteImport.update({
    id: '/zusatzfragen',
    path: '/zusatzfragen',
    getParentRoute: () => ChampionshipRoute,
  } as any)
const ChampionshipIndexRouteRoute = ChampionshipIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => ChampionshipRoute,
} as any)
const ChampionshipTippsChar123SlugChar125RouteRoute =
  ChampionshipTippsChar123SlugChar125RouteRouteImport.update({
    id: '/tipps/{-$slug}',
    path: '/tipps/{-$slug}',
    getParentRoute: () => ChampionshipRoute,
  } as any)
const ChampionshipSpieleNrRouteRoute =
  ChampionshipSpieleNrRouteRouteImport.update({
    id: '/spiele/$nr',
    path: '/spiele/$nr',
    getParentRoute: () => ChampionshipRoute,
  } as any)
const ChampionshipSpieleIndexRouteRoute =
  ChampionshipSpieleIndexRouteRouteImport.update({
    id: '/spiele/',
    path: '/spiele',
    getParentRoute: () => ChampionshipRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChampionshipIndexRouteRoute
  '/login': typeof LoginRoute
  '/zusatzfragen': typeof ChampionshipZusatzfragenRouteRoute
  '/tabelle': typeof ChampionshipTabelleRoute
  '/archiv/$slug': typeof ArchivSlugRoute
  '/archiv/': typeof ArchivIndexRoute
  '/spiele/': typeof ChampionshipSpieleIndexRouteRoute
  '/spiele/$nr': typeof ChampionshipSpieleNrRouteRoute
  '/tipps/{-$slug}': typeof ChampionshipTippsChar123SlugChar125RouteRoute
}
export interface FileRoutesByTo {
  '/': typeof ChampionshipIndexRouteRoute
  '/login': typeof LoginRoute
  '/zusatzfragen': typeof ChampionshipZusatzfragenRouteRoute
  '/tabelle': typeof ChampionshipTabelleRoute
  '/archiv/$slug': typeof ArchivSlugRoute
  '/archiv': typeof ArchivIndexRoute
  '/spiele': typeof ChampionshipSpieleIndexRouteRoute
  '/spiele/$nr': typeof ChampionshipSpieleNrRouteRoute
  '/tipps/{-$slug}': typeof ChampionshipTippsChar123SlugChar125RouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_championship': typeof ChampionshipRouteWithChildren
  '/login': typeof LoginRoute
  '/_championship/': typeof ChampionshipIndexRouteRoute
  '/_championship/zusatzfragen': typeof ChampionshipZusatzfragenRouteRoute
  '/_championship/tabelle': typeof ChampionshipTabelleRoute
  '/archiv/$slug': typeof ArchivSlugRoute
  '/archiv/': typeof ArchivIndexRoute
  '/_championship/spiele/': typeof ChampionshipSpieleIndexRouteRoute
  '/_championship/spiele/$nr': typeof ChampionshipSpieleNrRouteRoute
  '/_championship/tipps/{-$slug}': typeof ChampionshipTippsChar123SlugChar125RouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/zusatzfragen'
    | '/tabelle'
    | '/archiv/$slug'
    | '/archiv/'
    | '/spiele/'
    | '/spiele/$nr'
    | '/tipps/{-$slug}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/zusatzfragen'
    | '/tabelle'
    | '/archiv/$slug'
    | '/archiv'
    | '/spiele'
    | '/spiele/$nr'
    | '/tipps/{-$slug}'
  id:
    | '__root__'
    | '/_championship'
    | '/login'
    | '/_championship/'
    | '/_championship/zusatzfragen'
    | '/_championship/tabelle'
    | '/archiv/$slug'
    | '/archiv/'
    | '/_championship/spiele/'
    | '/_championship/spiele/$nr'
    | '/_championship/tipps/{-$slug}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChampionshipRoute: typeof ChampionshipRouteWithChildren
  LoginRoute: typeof LoginRoute
  ArchivSlugRoute: typeof ArchivSlugRoute
  ArchivIndexRoute: typeof ArchivIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_championship': {
      id: '/_championship'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChampionshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archiv/': {
      id: '/archiv/'
      path: '/archiv'
      fullPath: '/archiv/'
      preLoaderRoute: typeof ArchivIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archiv/$slug': {
      id: '/archiv/$slug'
      path: '/archiv/$slug'
      fullPath: '/archiv/$slug'
      preLoaderRoute: typeof ArchivSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_championship/tabelle': {
      id: '/_championship/tabelle'
      path: '/tabelle'
      fullPath: '/tabelle'
      preLoaderRoute: typeof ChampionshipTabelleRouteImport
      parentRoute: typeof ChampionshipRoute
    }
    '/_championship/zusatzfragen': {
      id: '/_championship/zusatzfragen'
      path: '/zusatzfragen'
      fullPath: '/zusatzfragen'
      preLoaderRoute: typeof ChampionshipZusatzfragenRouteRouteImport
      parentRoute: typeof ChampionshipRoute
    }
    '/_championship/': {
      id: '/_championship/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChampionshipIndexRouteRouteImport
      parentRoute: typeof ChampionshipRoute
    }
    '/_championship/tipps/{-$slug}': {
      id: '/_championship/tipps/{-$slug}'
      path: '/tipps/{-$slug}'
      fullPath: '/tipps/{-$slug}'
      preLoaderRoute: typeof ChampionshipTippsChar123SlugChar125RouteRouteImport
      parentRoute: typeof ChampionshipRoute
    }
    '/_championship/spiele/$nr': {
      id: '/_championship/spiele/$nr'
      path: '/spiele/$nr'
      fullPath: '/spiele/$nr'
      preLoaderRoute: typeof ChampionshipSpieleNrRouteRouteImport
      parentRoute: typeof ChampionshipRoute
    }
    '/_championship/spiele/': {
      id: '/_championship/spiele/'
      path: '/spiele'
      fullPath: '/spiele/'
      preLoaderRoute: typeof ChampionshipSpieleIndexRouteRouteImport
      parentRoute: typeof ChampionshipRoute
    }
  }
}

interface ChampionshipRouteChildren {
  ChampionshipIndexRouteRoute: typeof ChampionshipIndexRouteRoute
  ChampionshipZusatzfragenRouteRoute: typeof ChampionshipZusatzfragenRouteRoute
  ChampionshipTabelleRoute: typeof ChampionshipTabelleRoute
  ChampionshipSpieleIndexRouteRoute: typeof ChampionshipSpieleIndexRouteRoute
  ChampionshipSpieleNrRouteRoute: typeof ChampionshipSpieleNrRouteRoute
  ChampionshipTippsChar123SlugChar125RouteRoute: typeof ChampionshipTippsChar123SlugChar125RouteRoute
}

const ChampionshipRouteChildren: ChampionshipRouteChildren = {
  ChampionshipIndexRouteRoute: ChampionshipIndexRouteRoute,
  ChampionshipZusatzfragenRouteRoute: ChampionshipZusatzfragenRouteRoute,
  ChampionshipTabelleRoute: ChampionshipTabelleRoute,
  ChampionshipSpieleIndexRouteRoute: ChampionshipSpieleIndexRouteRoute,
  ChampionshipSpieleNrRouteRoute: ChampionshipSpieleNrRouteRoute,
  ChampionshipTippsChar123SlugChar125RouteRoute:
    ChampionshipTippsChar123SlugChar125RouteRoute,
}

const ChampionshipRouteWithChildren = ChampionshipRoute._addFileChildren(
  ChampionshipRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChampionshipRoute: ChampionshipRouteWithChildren,
  LoginRoute: LoginRoute,
  ArchivSlugRoute: ArchivSlugRoute,
  ArchivIndexRoute: ArchivIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
