/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChampionshipRouteImport } from './routes/_championship'
import { Route as ArchivIndexRouteImport } from './routes/archiv.index'
import { Route as ChampionshipIndexRouteImport } from './routes/_championship/index'
import { Route as ArchivSlugRouteImport } from './routes/archiv.$slug'
import { Route as ChampionshipZusatzfragenRouteImport } from './routes/_championship/zusatzfragen'
import { Route as ChampionshipTabelleRouteImport } from './routes/_championship/tabelle'
import { Route as ChampionshipSpieleIndexRouteImport } from './routes/_championship/spiele.index'
import { Route as ChampionshipTippsChar123SlugChar125RouteImport } from './routes/_championship/tipps.{-$slug}'
import { Route as ChampionshipSpieleNrRouteImport } from './routes/_championship/spiele.$nr'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionshipRoute = ChampionshipRouteImport.update({
  id: '/_championship',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivIndexRoute = ArchivIndexRouteImport.update({
  id: '/archiv/',
  path: '/archiv/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionshipIndexRoute = ChampionshipIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChampionshipRoute,
} as any)
const ArchivSlugRoute = ArchivSlugRouteImport.update({
  id: '/archiv/$slug',
  path: '/archiv/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionshipZusatzfragenRoute =
  ChampionshipZusatzfragenRouteImport.update({
    id: '/zusatzfragen',
    path: '/zusatzfragen',
    getParentRoute: () => ChampionshipRoute,
  } as any)
const ChampionshipTabelleRoute = ChampionshipTabelleRouteImport.update({
  id: '/tabelle',
  path: '/tabelle',
  getParentRoute: () => ChampionshipRoute,
} as any)
const ChampionshipSpieleIndexRoute = ChampionshipSpieleIndexRouteImport.update({
  id: '/spiele/',
  path: '/spiele/',
  getParentRoute: () => ChampionshipRoute,
} as any)
const ChampionshipTippsChar123SlugChar125Route =
  ChampionshipTippsChar123SlugChar125RouteImport.update({
    id: '/tipps/{-$slug}',
    path: '/tipps/{-$slug}',
    getParentRoute: () => ChampionshipRoute,
  } as any)
const ChampionshipSpieleNrRoute = ChampionshipSpieleNrRouteImport.update({
  id: '/spiele/$nr',
  path: '/spiele/$nr',
  getParentRoute: () => ChampionshipRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChampionshipIndexRoute
  '/login': typeof LoginRoute
  '/tabelle': typeof ChampionshipTabelleRoute
  '/zusatzfragen': typeof ChampionshipZusatzfragenRoute
  '/archiv/$slug': typeof ArchivSlugRoute
  '/archiv/': typeof ArchivIndexRoute
  '/spiele/$nr': typeof ChampionshipSpieleNrRoute
  '/tipps/{-$slug}': typeof ChampionshipTippsChar123SlugChar125Route
  '/spiele/': typeof ChampionshipSpieleIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/tabelle': typeof ChampionshipTabelleRoute
  '/zusatzfragen': typeof ChampionshipZusatzfragenRoute
  '/archiv/$slug': typeof ArchivSlugRoute
  '/': typeof ChampionshipIndexRoute
  '/archiv': typeof ArchivIndexRoute
  '/spiele/$nr': typeof ChampionshipSpieleNrRoute
  '/tipps/{-$slug}': typeof ChampionshipTippsChar123SlugChar125Route
  '/spiele': typeof ChampionshipSpieleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_championship': typeof ChampionshipRouteWithChildren
  '/login': typeof LoginRoute
  '/_championship/tabelle': typeof ChampionshipTabelleRoute
  '/_championship/zusatzfragen': typeof ChampionshipZusatzfragenRoute
  '/archiv/$slug': typeof ArchivSlugRoute
  '/_championship/': typeof ChampionshipIndexRoute
  '/archiv/': typeof ArchivIndexRoute
  '/_championship/spiele/$nr': typeof ChampionshipSpieleNrRoute
  '/_championship/tipps/{-$slug}': typeof ChampionshipTippsChar123SlugChar125Route
  '/_championship/spiele/': typeof ChampionshipSpieleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tabelle'
    | '/zusatzfragen'
    | '/archiv/$slug'
    | '/archiv/'
    | '/spiele/$nr'
    | '/tipps/{-$slug}'
    | '/spiele/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/tabelle'
    | '/zusatzfragen'
    | '/archiv/$slug'
    | '/'
    | '/archiv'
    | '/spiele/$nr'
    | '/tipps/{-$slug}'
    | '/spiele'
  id:
    | '__root__'
    | '/_championship'
    | '/login'
    | '/_championship/tabelle'
    | '/_championship/zusatzfragen'
    | '/archiv/$slug'
    | '/_championship/'
    | '/archiv/'
    | '/_championship/spiele/$nr'
    | '/_championship/tipps/{-$slug}'
    | '/_championship/spiele/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChampionshipRoute: typeof ChampionshipRouteWithChildren
  LoginRoute: typeof LoginRoute
  ArchivSlugRoute: typeof ArchivSlugRoute
  ArchivIndexRoute: typeof ArchivIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_championship': {
      id: '/_championship'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChampionshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archiv/': {
      id: '/archiv/'
      path: '/archiv'
      fullPath: '/archiv/'
      preLoaderRoute: typeof ArchivIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_championship/': {
      id: '/_championship/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChampionshipIndexRouteImport
      parentRoute: typeof ChampionshipRoute
    }
    '/archiv/$slug': {
      id: '/archiv/$slug'
      path: '/archiv/$slug'
      fullPath: '/archiv/$slug'
      preLoaderRoute: typeof ArchivSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_championship/zusatzfragen': {
      id: '/_championship/zusatzfragen'
      path: '/zusatzfragen'
      fullPath: '/zusatzfragen'
      preLoaderRoute: typeof ChampionshipZusatzfragenRouteImport
      parentRoute: typeof ChampionshipRoute
    }
    '/_championship/tabelle': {
      id: '/_championship/tabelle'
      path: '/tabelle'
      fullPath: '/tabelle'
      preLoaderRoute: typeof ChampionshipTabelleRouteImport
      parentRoute: typeof ChampionshipRoute
    }
    '/_championship/spiele/': {
      id: '/_championship/spiele/'
      path: '/spiele'
      fullPath: '/spiele/'
      preLoaderRoute: typeof ChampionshipSpieleIndexRouteImport
      parentRoute: typeof ChampionshipRoute
    }
    '/_championship/tipps/{-$slug}': {
      id: '/_championship/tipps/{-$slug}'
      path: '/tipps/{-$slug}'
      fullPath: '/tipps/{-$slug}'
      preLoaderRoute: typeof ChampionshipTippsChar123SlugChar125RouteImport
      parentRoute: typeof ChampionshipRoute
    }
    '/_championship/spiele/$nr': {
      id: '/_championship/spiele/$nr'
      path: '/spiele/$nr'
      fullPath: '/spiele/$nr'
      preLoaderRoute: typeof ChampionshipSpieleNrRouteImport
      parentRoute: typeof ChampionshipRoute
    }
  }
}

interface ChampionshipRouteChildren {
  ChampionshipTabelleRoute: typeof ChampionshipTabelleRoute
  ChampionshipZusatzfragenRoute: typeof ChampionshipZusatzfragenRoute
  ChampionshipIndexRoute: typeof ChampionshipIndexRoute
  ChampionshipSpieleNrRoute: typeof ChampionshipSpieleNrRoute
  ChampionshipTippsChar123SlugChar125Route: typeof ChampionshipTippsChar123SlugChar125Route
  ChampionshipSpieleIndexRoute: typeof ChampionshipSpieleIndexRoute
}

const ChampionshipRouteChildren: ChampionshipRouteChildren = {
  ChampionshipTabelleRoute: ChampionshipTabelleRoute,
  ChampionshipZusatzfragenRoute: ChampionshipZusatzfragenRoute,
  ChampionshipIndexRoute: ChampionshipIndexRoute,
  ChampionshipSpieleNrRoute: ChampionshipSpieleNrRoute,
  ChampionshipTippsChar123SlugChar125Route:
    ChampionshipTippsChar123SlugChar125Route,
  ChampionshipSpieleIndexRoute: ChampionshipSpieleIndexRoute,
}

const ChampionshipRouteWithChildren = ChampionshipRoute._addFileChildren(
  ChampionshipRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChampionshipRoute: ChampionshipRouteWithChildren,
  LoginRoute: LoginRoute,
  ArchivSlugRoute: ArchivSlugRoute,
  ArchivIndexRoute: ArchivIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
