/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as FrontRouteImport } from './routes/_front'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as ManagerSlugRouteImport } from './routes/manager/$slug'
import { Route as ManagerStammdatenTurniereRouteImport } from './routes/manager/stammdaten/turniere'
import { Route as ManagerStammdatenSpielerRouteImport } from './routes/manager/stammdaten/spieler'
import { Route as ManagerStammdatenRegelwerkeRouteImport } from './routes/manager/stammdaten/regelwerke'
import { Route as ManagerSlugTurnierRouteImport } from './routes/manager/$slug/turnier'
import { Route as FrontauthLoginRouteImport } from './routes/_front/(auth)/login'

const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontRoute = FrontRouteImport.update({
  id: '/_front',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerSlugRoute = ManagerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerStammdatenTurniereRoute =
  ManagerStammdatenTurniereRouteImport.update({
    id: '/stammdaten/turniere',
    path: '/stammdaten/turniere',
    getParentRoute: () => ManagerRoute,
  } as any)
const ManagerStammdatenSpielerRoute =
  ManagerStammdatenSpielerRouteImport.update({
    id: '/stammdaten/spieler',
    path: '/stammdaten/spieler',
    getParentRoute: () => ManagerRoute,
  } as any)
const ManagerStammdatenRegelwerkeRoute =
  ManagerStammdatenRegelwerkeRouteImport.update({
    id: '/stammdaten/regelwerke',
    path: '/stammdaten/regelwerke',
    getParentRoute: () => ManagerRoute,
  } as any)
const ManagerSlugTurnierRoute = ManagerSlugTurnierRouteImport.update({
  id: '/turnier',
  path: '/turnier',
  getParentRoute: () => ManagerSlugRoute,
} as any)
const FrontauthLoginRoute = FrontauthLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => FrontRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager/$slug': typeof ManagerSlugRouteWithChildren
  '/manager/': typeof ManagerIndexRoute
  '/login': typeof FrontauthLoginRoute
  '/manager/$slug/turnier': typeof ManagerSlugTurnierRoute
  '/manager/stammdaten/regelwerke': typeof ManagerStammdatenRegelwerkeRoute
  '/manager/stammdaten/spieler': typeof ManagerStammdatenSpielerRoute
  '/manager/stammdaten/turniere': typeof ManagerStammdatenTurniereRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manager/$slug': typeof ManagerSlugRouteWithChildren
  '/manager': typeof ManagerIndexRoute
  '/login': typeof FrontauthLoginRoute
  '/manager/$slug/turnier': typeof ManagerSlugTurnierRoute
  '/manager/stammdaten/regelwerke': typeof ManagerStammdatenRegelwerkeRoute
  '/manager/stammdaten/spieler': typeof ManagerStammdatenSpielerRoute
  '/manager/stammdaten/turniere': typeof ManagerStammdatenTurniereRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_front': typeof FrontRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/manager/$slug': typeof ManagerSlugRouteWithChildren
  '/manager/': typeof ManagerIndexRoute
  '/_front/(auth)/login': typeof FrontauthLoginRoute
  '/manager/$slug/turnier': typeof ManagerSlugTurnierRoute
  '/manager/stammdaten/regelwerke': typeof ManagerStammdatenRegelwerkeRoute
  '/manager/stammdaten/spieler': typeof ManagerStammdatenSpielerRoute
  '/manager/stammdaten/turniere': typeof ManagerStammdatenTurniereRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manager'
    | '/manager/$slug'
    | '/manager/'
    | '/login'
    | '/manager/$slug/turnier'
    | '/manager/stammdaten/regelwerke'
    | '/manager/stammdaten/spieler'
    | '/manager/stammdaten/turniere'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manager/$slug'
    | '/manager'
    | '/login'
    | '/manager/$slug/turnier'
    | '/manager/stammdaten/regelwerke'
    | '/manager/stammdaten/spieler'
    | '/manager/stammdaten/turniere'
  id:
    | '__root__'
    | '/'
    | '/_front'
    | '/manager'
    | '/manager/$slug'
    | '/manager/'
    | '/_front/(auth)/login'
    | '/manager/$slug/turnier'
    | '/manager/stammdaten/regelwerke'
    | '/manager/stammdaten/spieler'
    | '/manager/stammdaten/turniere'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FrontRoute: typeof FrontRouteWithChildren
  ManagerRoute: typeof ManagerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_front': {
      id: '/_front'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/$slug': {
      id: '/manager/$slug'
      path: '/$slug'
      fullPath: '/manager/$slug'
      preLoaderRoute: typeof ManagerSlugRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/stammdaten/turniere': {
      id: '/manager/stammdaten/turniere'
      path: '/stammdaten/turniere'
      fullPath: '/manager/stammdaten/turniere'
      preLoaderRoute: typeof ManagerStammdatenTurniereRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/stammdaten/spieler': {
      id: '/manager/stammdaten/spieler'
      path: '/stammdaten/spieler'
      fullPath: '/manager/stammdaten/spieler'
      preLoaderRoute: typeof ManagerStammdatenSpielerRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/stammdaten/regelwerke': {
      id: '/manager/stammdaten/regelwerke'
      path: '/stammdaten/regelwerke'
      fullPath: '/manager/stammdaten/regelwerke'
      preLoaderRoute: typeof ManagerStammdatenRegelwerkeRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/$slug/turnier': {
      id: '/manager/$slug/turnier'
      path: '/turnier'
      fullPath: '/manager/$slug/turnier'
      preLoaderRoute: typeof ManagerSlugTurnierRouteImport
      parentRoute: typeof ManagerSlugRoute
    }
    '/_front/(auth)/login': {
      id: '/_front/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof FrontauthLoginRouteImport
      parentRoute: typeof FrontRoute
    }
  }
}

interface FrontRouteChildren {
  FrontauthLoginRoute: typeof FrontauthLoginRoute
}

const FrontRouteChildren: FrontRouteChildren = {
  FrontauthLoginRoute: FrontauthLoginRoute,
}

const FrontRouteWithChildren = FrontRoute._addFileChildren(FrontRouteChildren)

interface ManagerSlugRouteChildren {
  ManagerSlugTurnierRoute: typeof ManagerSlugTurnierRoute
}

const ManagerSlugRouteChildren: ManagerSlugRouteChildren = {
  ManagerSlugTurnierRoute: ManagerSlugTurnierRoute,
}

const ManagerSlugRouteWithChildren = ManagerSlugRoute._addFileChildren(
  ManagerSlugRouteChildren,
)

interface ManagerRouteChildren {
  ManagerSlugRoute: typeof ManagerSlugRouteWithChildren
  ManagerIndexRoute: typeof ManagerIndexRoute
  ManagerStammdatenRegelwerkeRoute: typeof ManagerStammdatenRegelwerkeRoute
  ManagerStammdatenSpielerRoute: typeof ManagerStammdatenSpielerRoute
  ManagerStammdatenTurniereRoute: typeof ManagerStammdatenTurniereRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerSlugRoute: ManagerSlugRouteWithChildren,
  ManagerIndexRoute: ManagerIndexRoute,
  ManagerStammdatenRegelwerkeRoute: ManagerStammdatenRegelwerkeRoute,
  ManagerStammdatenSpielerRoute: ManagerStammdatenSpielerRoute,
  ManagerStammdatenTurniereRoute: ManagerStammdatenTurniereRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FrontRoute: FrontRouteWithChildren,
  ManagerRoute: ManagerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
