/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as FrontRouteImport } from './routes/_front'
import { Route as FrontIndexRouteImport } from './routes/_front/index'
import { Route as ManagerChar123SlugChar125RouteImport } from './routes/manager/{-$slug}'
import { Route as ManagerChar123SlugChar125IndexRouteImport } from './routes/manager/{-$slug}/index'
import { Route as ManagerChar123SlugChar125SpieleRouteImport } from './routes/manager/{-$slug}/spiele'
import { Route as ManagerStammdatenTurniereRouteImport } from './routes/manager/stammdaten/turniere'
import { Route as FrontauthLoginRouteImport } from './routes/_front/(auth)/login'
import { Route as ManagerStammdatenTeamsIndexRouteImport } from './routes/manager/stammdaten/teams/index'
import { Route as ManagerStammdatenLigenIndexRouteImport } from './routes/manager/stammdaten/ligen/index'

const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontRoute = FrontRouteImport.update({
  id: '/_front',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontIndexRoute = FrontIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrontRoute,
} as any)
const ManagerChar123SlugChar125Route =
  ManagerChar123SlugChar125RouteImport.update({
    id: '/{-$slug}',
    path: '/{-$slug}',
    getParentRoute: () => ManagerRoute,
  } as any)
const ManagerChar123SlugChar125IndexRoute =
  ManagerChar123SlugChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ManagerChar123SlugChar125Route,
  } as any)
const ManagerChar123SlugChar125SpieleRoute =
  ManagerChar123SlugChar125SpieleRouteImport.update({
    id: '/spiele',
    path: '/spiele',
    getParentRoute: () => ManagerChar123SlugChar125Route,
  } as any)
const ManagerStammdatenTurniereRoute =
  ManagerStammdatenTurniereRouteImport.update({
    id: '/stammdaten/turniere',
    path: '/stammdaten/turniere',
    getParentRoute: () => ManagerRoute,
  } as any)
const FrontauthLoginRoute = FrontauthLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => FrontRoute,
} as any)
const ManagerStammdatenTeamsIndexRoute =
  ManagerStammdatenTeamsIndexRouteImport.update({
    id: '/stammdaten/teams/',
    path: '/stammdaten/teams/',
    getParentRoute: () => ManagerRoute,
  } as any)
const ManagerStammdatenLigenIndexRoute =
  ManagerStammdatenLigenIndexRouteImport.update({
    id: '/stammdaten/ligen/',
    path: '/stammdaten/ligen/',
    getParentRoute: () => ManagerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof FrontIndexRoute
  '/manager': typeof ManagerRouteWithChildren
  '/manager/{-$slug}': typeof ManagerChar123SlugChar125RouteWithChildren
  '/login': typeof FrontauthLoginRoute
  '/manager/stammdaten/turniere': typeof ManagerStammdatenTurniereRoute
  '/manager/{-$slug}/spiele': typeof ManagerChar123SlugChar125SpieleRoute
  '/manager/{-$slug}/': typeof ManagerChar123SlugChar125IndexRoute
  '/manager/stammdaten/ligen/': typeof ManagerStammdatenLigenIndexRoute
  '/manager/stammdaten/teams/': typeof ManagerStammdatenTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/manager': typeof ManagerRouteWithChildren
  '/': typeof FrontIndexRoute
  '/login': typeof FrontauthLoginRoute
  '/manager/stammdaten/turniere': typeof ManagerStammdatenTurniereRoute
  '/manager/{-$slug}/spiele': typeof ManagerChar123SlugChar125SpieleRoute
  '/manager/{-$slug}': typeof ManagerChar123SlugChar125IndexRoute
  '/manager/stammdaten/ligen': typeof ManagerStammdatenLigenIndexRoute
  '/manager/stammdaten/teams': typeof ManagerStammdatenTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_front': typeof FrontRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/manager/{-$slug}': typeof ManagerChar123SlugChar125RouteWithChildren
  '/_front/': typeof FrontIndexRoute
  '/_front/(auth)/login': typeof FrontauthLoginRoute
  '/manager/stammdaten/turniere': typeof ManagerStammdatenTurniereRoute
  '/manager/{-$slug}/spiele': typeof ManagerChar123SlugChar125SpieleRoute
  '/manager/{-$slug}/': typeof ManagerChar123SlugChar125IndexRoute
  '/manager/stammdaten/ligen/': typeof ManagerStammdatenLigenIndexRoute
  '/manager/stammdaten/teams/': typeof ManagerStammdatenTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manager'
    | '/manager/{-$slug}'
    | '/login'
    | '/manager/stammdaten/turniere'
    | '/manager/{-$slug}/spiele'
    | '/manager/{-$slug}/'
    | '/manager/stammdaten/ligen/'
    | '/manager/stammdaten/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/manager'
    | '/'
    | '/login'
    | '/manager/stammdaten/turniere'
    | '/manager/{-$slug}/spiele'
    | '/manager/{-$slug}'
    | '/manager/stammdaten/ligen'
    | '/manager/stammdaten/teams'
  id:
    | '__root__'
    | '/_front'
    | '/manager'
    | '/manager/{-$slug}'
    | '/_front/'
    | '/_front/(auth)/login'
    | '/manager/stammdaten/turniere'
    | '/manager/{-$slug}/spiele'
    | '/manager/{-$slug}/'
    | '/manager/stammdaten/ligen/'
    | '/manager/stammdaten/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FrontRoute: typeof FrontRouteWithChildren
  ManagerRoute: typeof ManagerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_front': {
      id: '/_front'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_front/': {
      id: '/_front/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FrontIndexRouteImport
      parentRoute: typeof FrontRoute
    }
    '/manager/{-$slug}': {
      id: '/manager/{-$slug}'
      path: '/{-$slug}'
      fullPath: '/manager/{-$slug}'
      preLoaderRoute: typeof ManagerChar123SlugChar125RouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/{-$slug}/': {
      id: '/manager/{-$slug}/'
      path: '/'
      fullPath: '/manager/{-$slug}/'
      preLoaderRoute: typeof ManagerChar123SlugChar125IndexRouteImport
      parentRoute: typeof ManagerChar123SlugChar125Route
    }
    '/manager/{-$slug}/spiele': {
      id: '/manager/{-$slug}/spiele'
      path: '/spiele'
      fullPath: '/manager/{-$slug}/spiele'
      preLoaderRoute: typeof ManagerChar123SlugChar125SpieleRouteImport
      parentRoute: typeof ManagerChar123SlugChar125Route
    }
    '/manager/stammdaten/turniere': {
      id: '/manager/stammdaten/turniere'
      path: '/stammdaten/turniere'
      fullPath: '/manager/stammdaten/turniere'
      preLoaderRoute: typeof ManagerStammdatenTurniereRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_front/(auth)/login': {
      id: '/_front/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof FrontauthLoginRouteImport
      parentRoute: typeof FrontRoute
    }
    '/manager/stammdaten/teams/': {
      id: '/manager/stammdaten/teams/'
      path: '/stammdaten/teams'
      fullPath: '/manager/stammdaten/teams/'
      preLoaderRoute: typeof ManagerStammdatenTeamsIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/stammdaten/ligen/': {
      id: '/manager/stammdaten/ligen/'
      path: '/stammdaten/ligen'
      fullPath: '/manager/stammdaten/ligen/'
      preLoaderRoute: typeof ManagerStammdatenLigenIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
  }
}

interface FrontRouteChildren {
  FrontIndexRoute: typeof FrontIndexRoute
  FrontauthLoginRoute: typeof FrontauthLoginRoute
}

const FrontRouteChildren: FrontRouteChildren = {
  FrontIndexRoute: FrontIndexRoute,
  FrontauthLoginRoute: FrontauthLoginRoute,
}

const FrontRouteWithChildren = FrontRoute._addFileChildren(FrontRouteChildren)

interface ManagerChar123SlugChar125RouteChildren {
  ManagerChar123SlugChar125SpieleRoute: typeof ManagerChar123SlugChar125SpieleRoute
  ManagerChar123SlugChar125IndexRoute: typeof ManagerChar123SlugChar125IndexRoute
}

const ManagerChar123SlugChar125RouteChildren: ManagerChar123SlugChar125RouteChildren =
  {
    ManagerChar123SlugChar125SpieleRoute: ManagerChar123SlugChar125SpieleRoute,
    ManagerChar123SlugChar125IndexRoute: ManagerChar123SlugChar125IndexRoute,
  }

const ManagerChar123SlugChar125RouteWithChildren =
  ManagerChar123SlugChar125Route._addFileChildren(
    ManagerChar123SlugChar125RouteChildren,
  )

interface ManagerRouteChildren {
  ManagerChar123SlugChar125Route: typeof ManagerChar123SlugChar125RouteWithChildren
  ManagerStammdatenTurniereRoute: typeof ManagerStammdatenTurniereRoute
  ManagerStammdatenLigenIndexRoute: typeof ManagerStammdatenLigenIndexRoute
  ManagerStammdatenTeamsIndexRoute: typeof ManagerStammdatenTeamsIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerChar123SlugChar125Route: ManagerChar123SlugChar125RouteWithChildren,
  ManagerStammdatenTurniereRoute: ManagerStammdatenTurniereRoute,
  ManagerStammdatenLigenIndexRoute: ManagerStammdatenLigenIndexRoute,
  ManagerStammdatenTeamsIndexRoute: ManagerStammdatenTeamsIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  FrontRoute: FrontRouteWithChildren,
  ManagerRoute: ManagerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
